name: HammerSpade
author: AleksiReede
description: Adds craftable hammer and spade tools that dig in a 3x3 radius
version: '${project.version}'
main: io.github.aleksireede.hammerspade.Hammer
api-version: '1.21.11'
dependencies:
  server:
    HammerSharedLib:
      load: BEFORE
      required: true
      join-classpath: true
