name: Hammer
author: PoorgrammerDev
description: Adds craftable hammer and spade tools that dig in a 3x3 radius
version: '${project.version}'
main: io.github.poorgrammerdev.hammer.Hammer
api-version: '1.21.11'
commands:
  givehammer:
    usage: /givehammer <username> <type> [count] [damage]
    description: Give players hammers or spades.
    permission: hammer.givehammer
